


enum AlertDialogType { LOGOUT }
enum AppbarType { DEFAULT, BACK_BUTTON, HAMBURGER, TABVIEW, HAMBURGUER_NOTIFICATION }
enum ButtonType { DEFAULT, WITH_BORDER }
enum DividerType { DEFAULT }
enum DrawerType { DEFAULT }
enum LabelType { DEFAULT, SINGLE, DOUBLE, TEXT_ALIGNED_CENTER }
enum LegalWarningType { DEFAULT }
enum ModalType { CHOOSE_LOCAL, BOOKING_DETAILS, PERSONAL_DATA_USER, CHANGE_PASSWORD }
enum ShimmerType { APPOINTMENT, WORKER, SERVICE, SLOT }
enum SocialMediaType { DEFAULT }
enum StepperHeaderType { DEFAULT }
enum TextFormFieldType { DEFAULT, PASSWORD }
enum TileType { DRAWER, CHOOSE_PROFESSIONAL, CHOOSE_WORKER, CHOOSE_SERVICE, SHOW_BOOKING_HISTORY, CHOOSE_LOCAL, WORKER_SHIMMER, SERVICE_SHIMMER, CHOOSE_SLOT, SLOT_SHIMMER }