
enum UserRole { USER, WORKER, ADMIN}

enum PageNavigatorType { PUSH, PUSH_REPLACEMENT }

enum MyLabelType { H1, H2, H3, H4, H5, H6, BODY_LARGE , BODY_XLARGE, BODY_MEDIUM, BODY_SMALL, BODY_XSMALL }
enum MyTextFormFieldType { GENERAL, PREFIX, SUFFIX, PREFIX_SUFIX, PHONE, PASSWORD }
enum MyButtonType { FILLED, OUTLINED, IMAGE }
enum MyDividerType { GENERAL }
enum MyAppBarType { GENERAL, LEADING_ICON }